import { SourceDef } from "@/types";

export const SOURCES: SourceDef[] = [
  {
    id: "cs-courses",
    label: "CS Video Courses",
    description: "Free university-level CS courses with video lectures",
    icon: "GraduationCap",
    color: "emerald",
    owner: "Developer-Y",
    repo: "cs-video-courses",
    branch: "master",
    file: "README.md",
    parser: "heading-list",
  },
  {
    id: "scalable-arch",
    label: "Scalable Software Architecture",
    description: "Tech talks, papers and links on distributed systems & system design",
    icon: "Server",
    color: "blue",
    owner: "Developer-Y",
    repo: "Scalable-Software-Architecture",
    branch: "master",
    file: "README.md",
    parser: "heading-list",
  },
  {
    id: "tech-interviews",
    label: "Technical Interviews",
    description: "Resources and guides for acing technical interviews",
    icon: "Briefcase",
    color: "violet",
    owner: "Developer-Y",
    repo: "technical-interviews",
    branch: "master",
    file: "README.md",
    parser: "heading-list",
  },
  {
    id: "free-books",
    label: "Free Programming Books",
    description: "Free programming books in many languages and formats",
    icon: "BookOpen",
    color: "amber",
    owner: "EbookFoundation",
    repo: "free-programming-books",
    branch: "main",
    file: "books/free-programming-books-langs.md",
    parser: "heading-list",
  },
  {
    id: "build-your-own-x",
    label: "Build Your Own X",
    description: "Step-by-step guides to building your own technology from scratch",
    icon: "Wrench",
    color: "orange",
    owner: "codecrafters-io",
    repo: "build-your-own-x",
    branch: "master",
    file: "README.md",
    parser: "heading-list",
  },
  {
    id: "system-design-primer",
    label: "System Design Primer",
    description: "Learn how to design large-scale systems",
    icon: "Cpu",
    color: "cyan",
    owner: "donnemartin",
    repo: "system-design-primer",
    branch: "master",
    file: "README.md",
    parser: "heading-list",
  },
  {
    id: "interview-university",
    label: "Coding Interview University",
    description: "A complete CS study plan to become a software engineer",
    icon: "Target",
    color: "rose",
    owner: "jwasham",
    repo: "coding-interview-university",
    branch: "main",
    file: "README.md",
    parser: "heading-list",
  },
  {
    id: "awesome-python",
    label: "Awesome Python",
    description: "Curated list of Python frameworks, libraries, and resources",
    icon: "Code",
    color: "yellow",
    owner: "vinta",
    repo: "awesome-python",
    branch: "master",
    file: "README.md",
    parser: "heading-list",
  },
  {
    id: "awesome-react",
    label: "Awesome React",
    description: "Curated list of React resources, tools, and libraries",
    icon: "Layers",
    color: "sky",
    owner: "enaqx",
    repo: "awesome-react",
    branch: "master",
    file: "README.md",
    parser: "heading-list",
  },
  {
    id: "public-apis",
    label: "Public APIs",
    description: "A collective list of free APIs for software development",
    icon: "Plug",
    color: "teal",
    owner: "public-apis",
    repo: "public-apis",
    branch: "master",
    file: "README.md",
    parser: "heading-list",
  },
];
